```uml
@startuml
hide empty fields
hide empty methods
hide <<cmd>> circle
skinparam backgroundColor AntiqueWhite
skinparam class {
BackgroundColor<<CMD>> #AAFFAA
BorderColor<<CMD>> #222222
}

package "DB" as DB <<Database>>#CEF6F5{
  class "T:PT" as T1<<T,lightblue>>{
       PT情報を格納
       ..
  }
}
package "Web" as web <<frame>>#FF6347{
  class "P:PT" as P1<<P,colal>>{
       PT情報を表示
       ..
        +募集の参加者
       +募集期日を確認
       ..
       #join_menber()
  }
}
package "Discord" as discord <<frame>>#AAAAFF{
package USER <<Rectangle>> #FFFFFF{
}
  package "窓口.ch" as ch1 <<frame>>#DDDDFF{
      class "【PT募集申請】" as cmd1<<cmd>>{
       PTの募集内容を申請する。
       ..
       以下を必須事項として持つ
       +募集概要
          . 開催日
          . 内容
       +募集期日
       +募集人数
  }
}
}
  package "BOT" as bot #DDDDFF{
     package "" as bot1 <<node>>#DDDDFF{
}
     package "User情報管理システム" as bot4 <<node>>#DDDDFF{
}
     package "コミュニケーションシステム" as bot5 <<node>>#DDDDFF{
}
}
USER -> ch1
ch1---->cmd1
cmd1 -right-> bot1
bot1 -d-> T1
T1 <--> P1
P1 -d-> bot1
bot4<-d->bot1
bot4 -right-> bot5
bot5 -left->USER
@enduml
```
